Update README.md
aichner/Company-Homepage-Prototype pull request #14
Opened 2019-08-10 18:21 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [ ] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The current README is the default README from our template. #13 

**What is the new behavior (if this is a feature change)?**
- The README has been updated and now represents our organization. #13

2019-08-10 19:22 UTC, kleberbaum requested changes
It should be ok to merge after a few changes.

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +Have a bug or a feature request? Please first search for existing and closed issues. If your problem or idea is not addressed yet, [please open a new issue](https://github.com/aichner/Company-Homepag
Please check if there is a way to make a relative link instead of
https://github.com/aichner/Company-Homepage/issues/new/choose

And I think markdown files should also follow our guidelines for line length. max. 120c

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +Please read through our [contributing guidelines](https://github.com/aichner/Company-Homepage/blob/master/CONTRIBUTING.md). Included are directions for opening issues, coding standards, and notes on
Please check if there is a way to make a relative link instead of
https://github.com/aichner/Company-Homepage/blob/master/CONTRIBUTING.md

And I think markdown files should also follow our guidelines for line length. max. 120c

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +All HTML and CSS should conform to the [Code Guide](https://github.com/mdo/code-guide), maintained by [Mark Otto](https://github.com/mdo).
I think markdown files should also follow our guidelines for line length. max. 120c

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +For transparency into our release cycle and in striving to maintain backward compatibility, this repository is maintained under [the Semantic Versioning guidelines](https://semver.org/). Sometimes we
I think markdown files should also follow our guidelines for line length. max. 120c

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +We do not have any external contributors yet, but if you want your name to be here, feel free to [contribute to our project](#contributing).
And I think markdown files should also follow our guidelines for line length. max. 120c

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +  <a href="https://github.com/aichner/Company-Homepage/issues/new?template=feature_request.md">Request feature</a>
Please check if there is a way to make a relative link instead of
https://github.com/aichner/Company-Homepage/issues/new?

2019-08-10 19:22 UTC, kleberbaum commented on README.md
> +  <a href="https://github.com/aichner/Company-Homepage/issues/new?template=bug_report.md">Report bug</a>
Please check if there is a way to make a relative link instead of
https://github.com/aichner/Company-Homepage/issues/new?

2019-08-10 19:39 UTC, Aichnerc commented on README.md
> +Have a bug or a feature request? Please first search for existing and closed issues. If your problem or idea is not addressed yet, [please open a new issue](https://github.com/aichner/Company-Homepag
Relative links are possible, but limit the use of them. They do not work locally and when this readme is implemented in third-party pages.

A maximal character length for markdown is overkill. 🚀

2019-08-10 19:39 UTC, Aichnerc commented on README.md
> +Please read through our [contributing guidelines](https://github.com/aichner/Company-Homepage/blob/master/CONTRIBUTING.md). Included are directions for opening issues, coding standards, and notes on
Relative links are possible, but limit the use of them. They do not work locally and when this readme is implemented in third-party pages.

A maximal character length for markdown is overkill. 🚀

2019-08-10 19:39 UTC, Aichnerc commented on README.md
> +All HTML and CSS should conform to the [Code Guide](https://github.com/mdo/code-guide), maintained by [Mark Otto](https://github.com/mdo).
A maximal character length for markdown is overkill. 🚀

2019-08-10 19:39 UTC, Aichnerc commented on README.md
> +For transparency into our release cycle and in striving to maintain backward compatibility, this repository is maintained under [the Semantic Versioning guidelines](https://semver.org/). Sometimes we
A maximal character length for markdown is overkill. 🚀

2019-08-10 19:39 UTC, Aichnerc commented on README.md
> +We do not have any external contributors yet, but if you want your name to be here, feel free to [contribute to our project](#contributing).
A maximal character length for markdown is overkill. 🚀

2019-08-10 19:40 UTC, Aichnerc commented on README.md
> +  <a href="https://github.com/aichner/Company-Homepage/issues/new?template=feature_request.md">Request feature</a>
Relative links are possible, but limit the use of them. They do not work locally and when this readme is implemented in third-party pages.

2019-08-10 19:40 UTC, Aichnerc commented on README.md
> +  <a href="https://github.com/aichner/Company-Homepage/issues/new?template=bug_report.md">Report bug</a>
Relative links are possible, but limit the use of them. They do not work locally and when this readme is implemented in third-party pages.

2019-08-10 20:14 UTC, kleberbaum commented on README.md
> +All HTML and CSS should conform to the [Code Guide](https://github.com/mdo/code-guide), maintained by [Mark Otto](https://github.com/mdo).
> A maximal character length for markdown is overkill. 🚀

We allow up to 119 characters.

2019-08-10 20:14 UTC, kleberbaum commented on README.md
> +For transparency into our release cycle and in striving to maintain backward compatibility, this repository is maintained under [the Semantic Versioning guidelines](https://semver.org/). Sometimes we
> A maximal character length for markdown is overkill. 🚀

We allow up to 119 characters.

2019-08-10 20:14 UTC, kleberbaum commented on README.md
> +We do not have any external contributors yet, but if you want your name to be here, feel free to [contribute to our project](#contributing).
> A maximal character length for markdown is overkill. 🚀

We allow up to 119 characters.

2019-08-10 20:14 UTC, kleberbaum commented on README.md
> +Have a bug or a feature request? Please first search for existing and closed issues. If your problem or idea is not addressed yet, [please open a new issue](https://github.com/aichner/Company-Homepag
> A maximal character length for markdown is overkill. 🚀

We allow up to 119 characters.

2019-08-10 20:14 UTC, kleberbaum commented on README.md
> +Please read through our [contributing guidelines](https://github.com/aichner/Company-Homepage/blob/master/CONTRIBUTING.md). Included are directions for opening issues, coding standards, and notes on
> A maximal character length for markdown is overkill. 🚀

We allow up to 119 characters.

2019-08-11 13:16 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-08-11 13:16 UTC, merged