Improve footer 1
aichner/Company-Homepage-Prototype pull request #16
Opened 2019-08-10 19:19 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, there is no logo in the footer. #10 
- Currently, there is a missing line in the footer. #15 

**What is the new behavior (if this is a feature change)?**
- Our logo has been added to the footer. #10 
- The missing line has been added to the footer. #15

2019-08-10 19:19 UTC, Aichnerc reviewed
Looks fine to me

2019-08-10 20:24 UTC, kleberbaum requested changes
It should be ok to merge after a few changes.

2019-08-10 20:24 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +                            <img src={Logo} style={{ height: "2.5rem" }} />
Is it absolutely necessary to define this style in html?

2019-08-10 20:24 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +                                <a href="mailto:info@aichner-christian.com"><MDBIcon far icon="envelope" />info@aichner-christian.com</a>
Unnecessarily long line.
We allow up to 119 characters as this is the width of GitHub code review.

2019-08-11 07:40 UTC, Aichnerc commented on src/components/molecules/Footer/index.jsx
> +                            <img src={Logo} style={{ height: "2.5rem" }} />
Nah, I just copied it from the MDB Pro documentation. But you're right, it's way cleaner to define it in footer.scss.

2019-08-11 07:50 UTC, Aichnerc commented on src/components/molecules/Footer/index.jsx
> +                                <a href="mailto:info@aichner-christian.com"><MDBIcon far icon="envelope" />info@aichner-christian.com</a>
The entire file has been cleaned up regarding line length.

2019-08-11 08:08 UTC, Aichnerc reviewed
Everything looks fine to me

2019-08-11 13:07 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-08-11 13:07 UTC, merged