Add sections 1
aichner/Company-Homepage-Prototype pull request #30
Opened 2019-09-16 13:53 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The website has no section but the hero shot. #25 #26 
- The hero component does not fit the theme. #27 

**What is the new behavior (if this is a feature change)?**
- The website now has two additional sections. #25 #26 
- The hero component has been improved to fit the theme. #27

2019-09-16 14:11 UTC, Aichnerc reviewed
After a line-length change it should be okay.

2019-09-16 19:06 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2019-09-16 19:06 UTC, kleberbaum commented on package.json
> +    "react-particles-js": "^2.7.0",
ParticlesJS should be removed from package.

2019-09-22 17:17 UTC, Aichnerc commented on package.json
> +    "react-particles-js": "^2.7.0",
This problem has been resolved.

2019-09-22 18:14 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-09-22 18:15 UTC, kleberbaum approved these changes

2019-09-22 18:15 UTC, merged