Add personalized data 1
aichner/Company-Homepage-Prototype pull request #6
Opened 2019-08-03 17:57 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- All page content consists of our React-MDB-Template
- The `index.html` is the standard React template
- The favicon is the standard React icon

**What is the new behavior (if this is a feature change)?**
- Company data and logos have been added #4 
- The `index.html` has been updated
- An icon pack has replaced the old React favicon

2019-08-03 22:46 UTC, Aichnerc reviewed
Everything seems ok.

2019-08-05 09:28 UTC, kleberbaum requested changes
After this changes it should be ok to merge.

2019-08-05 09:28 UTC, kleberbaum commented on src/components/pages/HomePage/index.jsx
> +      null
NOTE: It would be appreciated to comment why a render function returns null.

2019-08-05 09:28 UTC, kleberbaum commented on public/fav/browserconfig.xml
> +<browserconfig><msapplication><tile><square70x70logo src="/ms-icon-70x70.png"/><square150x150logo src="/ms-icon-150x150.png"/><square310x310logo src="/ms-icon-310x310.png"/><TileColor>#ffffff</TileCo
Note: It would be much better with some line breaks.

2019-08-05 16:31 UTC, Aichnerc commented on src/components/pages/HomePage/index.jsx
> +      null
Well, because nothing should be displayed. Comment will be added.

2019-08-05 16:32 UTC, Aichnerc commented on public/fav/browserconfig.xml
> +<browserconfig><msapplication><tile><square70x70logo src="/ms-icon-70x70.png"/><square150x150logo src="/ms-icon-150x150.png"/><square310x310logo src="/ms-icon-310x310.png"/><TileColor>#ffffff</TileCo
Sure. Will be improved.

2019-08-05 18:50 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-08-05 19:26 UTC, merged