Add footer 1
aichner/Company-Homepage-Prototype pull request #8
Opened 2019-08-03 21:31 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The footer contains standard template placeholders #5 
- Roboto is the default font #7 

**What is the new behavior (if this is a feature change)?**
- The content of the footer has been updated #5 
- A new font-face (Gidole) has been erected, however, was not used as the default font because of its poor readability #7 

**Additional information**
- A bug that was present in the template has been discovered, locally fixed and reported to the template
https://github.com/aichner/React-MDB-Template/issues/4

2019-08-03 21:34 UTC, Aichnerc reviewed
Update required. (See comment)

2019-08-03 21:34 UTC, Aichnerc commented on src/components/molecules/Footer/footer.scss
> +footer {
I would like to have some better commentary here.

2019-08-03 21:35 UTC, Aichnerc commented on src/components/molecules/Footer/footer.scss
> +footer {
Better commentary has been added.

2019-08-05 09:34 UTC, kleberbaum requested changes
Add some line breaks and it should be ok to merge.

2019-08-05 09:34 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +                        href="https://api.whatsapp.com/send?phone=4368120502754&text=Hey%2C%20ich%20bin%20interessiert%20an%20einem%20Angebot%20eurer%20Agentur."
It would be much better with some line breaks.

2019-08-05 09:34 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +                        <p className="my-2 font-weight-bold gidole">Made with <i className="fas fa-heart pulse red-text" aria-hidden="true"></i> by us.</p>
It would be much better with some line breaks.

2019-08-05 18:53 UTC, Aichnerc commented on src/components/molecules/Footer/index.jsx
> +                        href="https://api.whatsapp.com/send?phone=4368120502754&text=Hey%2C%20ich%20bin%20interessiert%20an%20einem%20Angebot%20eurer%20Agentur."
Not possible with this href string - without making it look absolutely worse.

2019-08-05 18:59 UTC, Aichnerc commented on src/components/molecules/Footer/index.jsx
> +                        <p className="my-2 font-weight-bold gidole">Made with <i className="fas fa-heart pulse red-text" aria-hidden="true"></i> by us.</p>
Sure thing. Has been fixed.

2019-08-05 19:00 UTC, Aichnerc reviewed
Looks absolutely fine to me.

2019-08-05 19:35 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +                        href="https://api.whatsapp.com/send?phone=4368120502754&text=Hey%2C%20ich%20bin%20interessiert%20an%20einem%20Angebot%20eurer%20Agentur."
If a URL in a link has a line break, the link won't work. If a URL is longer than 80 characters (quite common), you're stuck with it.

Ref: https://developers.google.com/style/html-formatting

2019-08-05 19:35 UTC, merged

2019-08-05 19:40 UTC, kleberbaum reviewed
Should be ok to merge.

2019-08-05 19:42 UTC, Aichnerc reviewed
Seems fine to me